package org.isource.beans;
// Generated Nov 14, 2016 11:41:38 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Files generated by hbm2java
 */
public class Files implements java.io.Serializable {

    private int id;
    private String filepath;
    private String tablename;
    private String title;
    private Date created;
    private Date updated;
    private int formula_id;
    private String formula_title;

    public Files() {
    }

    public Files(int id, Date created, Date updated) {
        this.id = id;
        this.created = created;
        this.updated = updated;
    }

    public Files(int id, String filepath, String tablename, Date created, Date updated) {
        this.id = id;
        this.filepath = filepath;
        this.tablename = tablename;
        this.created = created;
        this.updated = updated;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFilepath() {
        return this.filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    public String getTablename() {
        return this.tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public int getFormula_id() {
        return formula_id;
    }

    public String getFormula_title() {
        return formula_title;
    }

    public void setFormula_id(int formula_id) {
        this.formula_id = formula_id;
    }

    public void setFormula_title(String formula_title) {
        this.formula_title = formula_title;
    }

}
